### ISSUE TITLE
Can't get X-Access-Token using $request

### ISSUE THREAD

**Issue by developer239** [Slim3/slim3#26]
How do I get X-Access-Token using `\Slim\Http\Request` object?

I got it working only like this:
```
    $request_headers = getallheaders();
    $accessToken = $request_headers["X-Access-Token"];
```

**Comment by vvakame** [comment]
Slim 3 is not a Slim framework. http://www.slimframework.com/

**Comment by developer239** [comment]
What?!

**Comment by developer239** [comment]
I am really sorry but that has to be THE WORST contribution on github ever. I can imagine that you just woke up. Saw some issues. Looked at the first one and was like "Meh, fuck this guy. This is not my problem."
